povar_blog/blog/urls.py
from django.urls import path
from .views import *
from django.views.decorators.cache import cache_page

app_name = 'blog'

urlpatterns = [
    path('comment/<int:pk>/', AddComment.as_view(), name='add_comment'),
    path('<slug:slug>/<slug:post_slug>/', PostDetailView.as_view(), name='post_single'),
    path('<slug:slug>/', PostListView.as_view(), name='post_list'),
    path('', cache_page(15 * 60)(HomeView.as_view()), name='home'),
    # path('', HomeView.as_view(), name='home'),
]

povar_blog/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('__debug__/', include('debug_toolbar.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('', include('contact.urls')),
    path('', include('blog.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

povar_blog/blog/models.py
from ckeditor.fields import RichTextField
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from django.utils import timezone
from mptt.models import MPTTModel, TreeForeignKey


class Category(MPTTModel):
    """Модель категории"""
    name = models.CharField(max_length=100)
    slug = models.SlugField(max_length=100)
    parent = TreeForeignKey(
        'self',
        on_delete=models.CASCADE,
        null=True,
        blank=True,
        related_name='children'
    )

    def __str__(self):
        return self.name

    class MPTTMeta:
        order_insertion_by = ['-name']

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'


class Tag(models.Model):
    """Модель Тегов"""
    name = models.CharField(max_length=100)
    slug = models.SlugField(max_length=100)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Тег'
        verbose_name_plural = 'Теги'


class Post(models.Model):
    """Модель постов"""
    author = models.ForeignKey(
        User,
        related_name='posts',
        on_delete=models.CASCADE
    )
    title = models.CharField(max_length=200)
    image = models.ImageField(upload_to='articles/')
    text = models.TextField()
    category = models.ForeignKey(
        Category,
        related_name='post',
        on_delete=models.SET_NULL,
        null=True
    )
    tags = models.ManyToManyField(Tag, related_name='post')
    created_at = models.DateTimeField(auto_now_add=True)
    slug = models.SlugField(max_length=200, default='')

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse(
            'blog:post_single',
            kwargs={
                'slug': self.category.slug,
                'post_slug': self.slug
            }
        )

    def get_comments(self):
        return self.comment.all()

    class Meta:
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'


class Recipe(models.Model):
    """Модель рецептов"""
    name = models.CharField(max_length=100)
    servis = models.CharField(max_length=50)
    prep_time = models.PositiveIntegerField(default=0)
    cook_time = models.PositiveIntegerField(default=0)
    ingredients = RichTextField()
    directions = RichTextField()
    post = models.ForeignKey(
        Post,
        related_name='recipe',
        on_delete=models.SET_NULL,
        null=True,
        blank=True
    )

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Рецепт'
        verbose_name_plural = 'Рецепты'


class Comment(models.Model):
    """Модель комментариев"""
    name = models.CharField(max_length=50)
    email = models.EmailField(max_length=100)
    website = models.CharField(max_length=150, blank=True, null=True)
    message = models.TextField(max_length=500)
    created_at = models.DateTimeField(default=timezone.now)
    post = models.ForeignKey(Post, related_name='comment', on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'

povar_blog/blog/forms.py
from django import forms
from .models import Comment


class CommentForm(forms.ModelForm):
    """Форма комментария"""
    class Meta:
        model = Comment
        exclude = ['created_at', 'post']
        widgets = {
            'name': forms.TextInput(attrs={'placeholder': 'Name'}),
            'email': forms.EmailInput(attrs={'placeholder': 'Email'}),
            'website': forms.TextInput(attrs={'placeholder': 'Website'}),
            'message': forms.Textarea(attrs={'placeholder': 'Message'}),
        }

povar_blog/blog/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView, CreateView
from .models import *
from .forms import CommentForm


class HomeView(ListView):
    model = Post
    # paginate_by = 10
    template_name = 'blog/home.html'


class PostListView(ListView):
    """Вывод списка постов"""
    model = Post

    def get_queryset(self):
        return Post.objects.filter(category__slug=self.kwargs.get('slug')).select_related('category')


class PostDetailView(DetailView):
    """Вывод одного поста"""
    model = Post
    context_object_name = 'post'
    slug_url_kwarg = 'post_slug'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = CommentForm
        return context


class AddComment(CreateView):
    """Добавление комментария"""
    model = Comment
    form_class = CommentForm
    success_url = '/'

    def form_valid(self, form):
        form.instance.post_id = self.kwargs.get('pk')
        self.object = form.save()
        return super().form_valid(form)

    def get_success_url(self):
        return self.object.post.get_absolute_url()

povar_blog/templates/blog/post_detail.html
{% extends 'base.html' %}
{% load static social_tags %}
{% block content %}
<!-- Single Post Section Begin -->
<section class="single-post spad">
    <div class="single-post__hero set-bg" data-setbg="{{ post.image.url }}"></div>
    <div class="container">
        <div class="row d-flex justify-content-center">
            <div class="col-lg-8">
                <div class="single-post__title">
                    <div class="single-post__title__meta">
                        <h2>{{ post.created_at|date:'j' }}</h2>
                        <span>{{ post.created_at|date:'M' }}</span>
                    </div>
                    <div class="single-post__title__text">
                        <ul class="label">
                            <li>{{ post.category }}</li>
                        </ul>
                        <h4>{{ post.title }}</h4>
                        <ul class="widget">
                            <li>by {{ post.author }}</li>
                            <li>3 min read</li>
                            <li>20 Comment</li>
                        </ul>
                    </div>
                </div>
                <div class="single-post__social__item">
                    {% get_social_links as social_links %}
                    <ul>
                        {% for item in social_links %}
                        <li><a href="{{ item.link }}"><img src="{{ item.icon.url }}"></a></li>
                        {% endfor %}
                    </ul>
                </div>
                <div class="single-post__top__text">
                    <p>{{ post.text|truncatewords:20 }}</p>
                </div>
                <div class="single-post__recipe__details">
                    {% for recipe in post.recipe.all %}
                    <div class="single-post__recipe__details__option">
                        <ul>
                            <li>
                                <h5><i class="fa fa-user-o"></i> SERVES</h5>
                                <span>{{ recipe.servis }}</span>
                            </li>
                            <li>
                                <h5><i class="fa fa-clock-o"></i> PREP TIME</h5>
                                <span>{{ recipe.prep_time }} minute</span>
                            </li>
                            <li>
                                <h5><i class="fa fa-clock-o"></i> Cook TIME</h5>
                                <span>{{ recipe.cook_time }} minute</span>
                            </li>
                            <li><a href="#" class="primary-btn"><i class="fa fa-print"></i> Read more</a></li>
                        </ul>
                    </div>

                    <div class="single-post__recipe__details__indegradients">
                        <h5>Ingredients</h5>
                        {{ recipe.ingredients|safe }}
                    </div>
                    <div class="single-post__recipe__details__direction">
                        <h5>Directions</h5>
                        {{ recipe.directions|safe }}
                    </div>
                    {% endfor %}
                </div>
                <div class="single-post__desc">
                    <p>{{ post.text }}</p>
                </div>
                <div class="single-post__tags">
                    {% for tag in post.tags.all %}
                    <a href="#">{{ tag.name }}</a>
                    {% endfor %}
                </div>
                <div class="single-post__next__previous">
                    <div class="row">
                        <div class="col-lg-6 col-md-6 col-sm-6">
                            <a href="#" class="single-post__previous">
                                <h6><span class="arrow_carrot-left"></span> Previous posts</h6>
                                <div class="single-post__previous__meta">
                                    <h4>08</h4>
                                    <span>Aug</span>
                                </div>
                                <div class="single-post__previous__text">
                                    <span>Dinner</span>
                                    <h5>The Best Weeknight Baked <br/>Potatoes, 3 Creative Ways</h5>
                                </div>
                            </a>
                        </div>
                        <div class="col-lg-6 col-md-6 col-sm-6">
                            <a href="#" class="single-post__next">
                                <h6>Next posts <span class="arrow_carrot-right"></span></h6>
                                <div class="single-post__next__meta">
                                    <h4>05</h4>
                                    <span>Aug</span>
                                </div>
                                <div class="single-post__next__text">
                                    <span>Smoothie</span>
                                    <h5>The $8 French Rosé I Buy in <br/>Bulk Every Summer</h5>
                                </div>
                            </a>
                        </div>
                    </div>
                </div>
                {% get_about as about %}
                <div class="single-post__author__profile">
                    <div class="single-post__author__profile__pic">
                        <img src="{{ about.get_first_image }}" alt="">
                    </div>
                    <div class="single-post__author__profile__text">
                        <h4>{{ about.name }}</h4>
                        <p>{{ about.mini_text|safe }}</p>
                        <div class="single-post__author__profile__social">
                            {% get_social_links as social_links %}
                            {% for item in social_links %}
                            <a href="{{ item.link }}"><img src="{{ item.icon.url }}"></a>
                            {% endfor %}
                        </div>
                    </div>
                </div>
                <div class="single-post__comment">
                    <div class="widget__title">
                        <h4>{{ post.get_comments.count }} Comment</h4>
                    </div>
                    {% for comment in post.get_comments %}
                    <div class="single-post__comment__item">
                        <div class="single-post__comment__item__pic">
                            <img src="{% static 'img/categories/cat-2.jpg' %}" alt="">
                        </div>
                        <div class="single-post__comment__item__text">
                            <h5>{{ comment.name }}</h5>
                            <span>{{ comment.created_at }}</span>
                            <p>{{ comment.message }}</p>
                        </div>
                    </div>
                    {% endfor %}
                </div>
                <div class="single-post__leave__comment">
                    <div class="widget__title">
                        <h4>Leave a comment</h4>
                    </div>
                    <form action="{% url 'blog:add_comment' pk=post.pk %}" method="POST">
                        {% csrf_token %}
                        <div class="input-list">
                            {{ form.name }}
                            {{ form.email }}
                            {{ form.website }}
                        </div>
                        {{ form.message }}
                        <button type="submit" class="site-btn">Submit</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- Single Post Section End -->
{% endblock content %}

povar_blog/templates/blog/post_list.html
{% extends 'base.html' %}

{% block content %}
    <!-- Categories Section Begin -->
    <section class="categories categories-grid spad">
        <div class="categories__post">
            <div class="container">
                <div class="categories__grid__post">
                    <div class="row">
                        <div class="col-lg-8 col-md-8">
                            <div class="breadcrumb__text">
                                <h2>Categories: <span>{{ post_list.first.category.name }}</span></h2>
                                <div class="breadcrumb__option">
                                    <a href="#">Home</a>
                                    <span>Recipes</span>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-lg-6 col-md-6 col-sm-6">
                                    {% for post in post_list %}
                                        <div class="categories__post__item">
                                            <div class="categories__post__item__pic small__item set-bg"
                                                data-setbg="{{ post.image.url }}">
                                                <div class="post__meta">
                                                    <h4>{{ post.created_at|date:'j' }}</h4>
                                                    <span>{{ post.created_at|date:'M' }}</span>
                                                </div>
                                            </div>
                                            <div class="categories__post__item__text">
                                                <span class="post__label">{{ post.category }}</span>
                                                <h3><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h3>
                                                <ul class="post__widget">
                                                    <li>by <span>{{ post.author }}</span></li>
                                                    <li>3 min read</li>
                                                    <li>20 Comment</li>
                                                </ul>
                                                <p>{{ post.text|truncatewords:20 }} ...</p>
                                            </div>
                                        </div>
                                    {% endfor %}
                                </div>

                                <div class="col-lg-12 text-center">
                                    <div class="load__more__btn">
                                        <a href="#">Load more</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                        {% include 'blog/include/sidebar.html' %}
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Categories Section End -->
{% endblock content%}