povar_blog/blog/urls.py
from django.urls import path
from .views import *
from django.views.decorators.cache import cache_page

app_name = 'blog'

urlpatterns = [
    path('comment/<int:pk>/', AddComment.as_view(), name='add_comment'),
    path('<slug:slug>/<slug:post_slug>/', PostDetailView.as_view(), name='post_single'),
    path('<slug:slug>/', PostListView.as_view(), name='post_list'),
    path('', cache_page(15 * 60)(HomeView.as_view()), name='home'),
    # path('', HomeView.as_view(), name='home'),
]

povar_blog/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('__debug__/', include('debug_toolbar.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('', include('contact.urls')),
    path('', include('blog.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

povar_blog/contact/urls.py
from django.urls import path
from .views import *

app_name = 'contact'

urlpatterns = [
    path('contact/', ContactView.as_view(), name='contact'),
    path('about/', AboutView.as_view(), name='about'),
    path('feedback/', CreateContact.as_view(), name='feedback'),
]

povar_blog/contact/models.py
from ckeditor.fields import RichTextField
from django.db import models


class ContactModel(models.Model):
    """Класс модели обратной связи"""
    name = models.CharField(max_length=50)
    email = models.EmailField()
    website = models.URLField(blank=True, null=True)
    message = models.TextField(max_length=5000)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.name} - {self.email}'

    class Meta:
        verbose_name = 'Отзыв'
        verbose_name_plural = 'Отзывы'


class ContactLink(models.Model):
    """Класс модели контактов"""
    icon = models.FileField(upload_to='icons/')
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Контакт'
        verbose_name_plural = 'Контакты'


class About(models.Model):
    """Класс модели о нас"""
    name = models.CharField(max_length=50, default='')
    text = RichTextField()
    mini_text = RichTextField()

    def get_first_image(self):
        item = self.about_images.first()
        return item.image.url

    def get_images(self):
        return self.about_images.order_by('pk')[1:]

    def __str__(self):
        return self.text[:20]

    class Meta:
        verbose_name = 'О нас'
        verbose_name_plural = 'О нас'


class ImageAbout(models.Model):
    """Класс модели изображений страницы о нас"""
    image = models.ImageField(upload_to='about/')
    page = models.ForeignKey(About, on_delete=models.CASCADE, related_name='about_images')
    alt = models.CharField(max_length=100)

    class Meta:
        verbose_name = 'Изображение'
        verbose_name_plural = 'Изображения'


class Social(models.Model):
    """Класс  модели соц сетей страницы о нас"""
    icon = models.FileField(upload_to='icons/')
    name = models.CharField(max_length=200)
    link = models.URLField()

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Социальная сеть'
        verbose_name_plural = 'Социальные сети'

povar_blog/contact/forms.py
from django import forms
from .models import *


class ContactForm(forms.ModelForm):
    class Meta:
        model = ContactModel
        fields = '__all__'

povar_blog/contact/views.py
from django.shortcuts import render
from django.views import View
from django.views.generic import CreateView

from .forms import ContactForm
from .models import *


class ContactView(View):
    def get(self, request):
        contacts = ContactLink.objects.all()
        form = ContactForm()
        return render(request, 'contact/contact.html', {'contacts': contacts, 'form': form})


class CreateContact(CreateView):
    """Форма добавления контактов"""
    form_class = ContactForm
    success_url = '/'


class AboutView(View):
    def get(self, request):
        about = About.objects.last()
        return render(request, 'contact/about.html', {'about': about})

povar_blog/templates/contact/about.html
{% extends 'base.html' %}
{% load social_tags %}

{% block content %}
    <section class="about spad">
        <div class="container">
            <div class="about__text">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="breadcrumb__text">
                            <h2>About me</h2>
                            <div class="breadcrumb__option">
                                <a href="#">Home</a>
                                <span>About</span>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-6">
                        <div class="about__pic__item__large">
                            <img src="{{ about.get_first_image }}" alt="">
                        </div>
                        <div class="about__pic">
                            {% for item in about.get_images %}
                                <div class="about__pic__item">
                                <img src="{{ item.image.url }}" alt="item.alt">
                            </div>
                            {% endfor %}
                        </div>
                    </div>
                    <div class="col-lg-6">
                        <div class="about__right__text">
                            <h2>Hello every one !!!</h2>
                            {{ about.text|safe }}
                            <div class="about__right__text__social">
                                {% get_social_links as social_links %}
                                {% for item in social_links %}
                                    <a href="{{ item.link }}"><img src="{{ item.icon.url }}"></a>
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock content%}

povar_blog/templates/contact/contact.html
{% extends 'base.html' %}

{% block content %}

<section class="contact spad">
    <div class="container">
        <div class="contact__text">
            <div class="row">
                <div class="col-lg-12">
                    <div class="breadcrumb__text">
                        <h2>Contact</h2>
                        <div class="breadcrumb__option">
                            <a href="#">Home</a>
                            <span>Contact</span>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-6 col-md-6">
<!--                    <div class="contact__map">-->
<!--                        <iframe-->
<!--                                src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d96748.5538666784!2d-74.25209557318462!3d40.73139236772185!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x89c25370329a0e1d%3A0xe1bcdc2adcfee473!2sNewark%2C%20NJ%2C%20USA!5e0!3m2!1sen!2sbd!4v1585643782289!5m2!1sen!2sbd"-->
<!--                                height="350" style="border:0;" allowfullscreen="" aria-hidden="false"-->
<!--                                tabindex="0">-->
<!--                            -->
<!--                        </iframe>-->
<!--                    </div>-->
                    <div class="contact__widget">
                        <ul>
                            {% for contact in contacts %}
                                <li>
<!--                                <i class="fa fa-map-marker"></i>-->
                                <img class="contact_icon" src="{{ contact.icon.url }}">
                                <span>{{ contact.name }}</span>
                            </li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
                <div class="col-lg-6 col-md-6">
                    <div class="contact__form">
                        <div class="contact__form__title">
                            <h2>gET IN TOUCH</h2>
                            <p>My experience with Realy is absolutely positive. The themes are beautifully designed
                                and well documented. Realy theme provides quick support.</p>
                        </div>
                        <form action="{% url 'contact:feedback' %}" method="POST">
<!--                            <input type="text" placeholder="Name">-->
<!--                            <input type="text" placeholder="Email">-->
<!--                            <input type="text" placeholder="Website">-->
<!--                            <textarea placeholder="Message"></textarea>-->
                            {% csrf_token %}
                            {{ form }}
                            <button type="submit" class="site-btn">Submit</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock content %}