povar_blog/blog/urls.py
from django.urls import path
from .views import *
from django.views.decorators.cache import cache_page

app_name = 'blog'

urlpatterns = [
    path('comment/<int:pk>/', AddComment.as_view(), name='add_comment'),
    path('<slug:slug>/<slug:post_slug>/', PostDetailView.as_view(), name='post_single'),
    path('<slug:slug>/', PostListView.as_view(), name='post_list'),
    path('', cache_page(15 * 60)(HomeView.as_view()), name='home'),
    # path('', HomeView.as_view(), name='home'),
]

povar_blog/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('__debug__/', include('debug_toolbar.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('', include('contact.urls')),
    path('', include('blog.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

povar_blog/contact/urls.py
from django.urls import path
from .views import *

app_name = 'contact'

urlpatterns = [
    path('contact/', ContactView.as_view(), name='contact'),
    path('about/', AboutView.as_view(), name='about'),
    path('feedback/', CreateContact.as_view(), name='feedback'),
]

povar_blog/blog/models.py
from ckeditor.fields import RichTextField
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from django.utils import timezone
from mptt.models import MPTTModel, TreeForeignKey


class Category(MPTTModel):
    """Модель категории"""
    name = models.CharField(max_length=100)
    slug = models.SlugField(max_length=100)
    parent = TreeForeignKey(
        'self',
        on_delete=models.CASCADE,
        null=True,
        blank=True,
        related_name='children'
    )

    def __str__(self):
        return self.name

    class MPTTMeta:
        order_insertion_by = ['-name']

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'


class Tag(models.Model):
    """Модель Тегов"""
    name = models.CharField(max_length=100)
    slug = models.SlugField(max_length=100)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Тег'
        verbose_name_plural = 'Теги'


class Post(models.Model):
    """Модель постов"""
    author = models.ForeignKey(
        User,
        related_name='posts',
        on_delete=models.CASCADE
    )
    title = models.CharField(max_length=200)
    image = models.ImageField(upload_to='articles/')
    text = models.TextField()
    category = models.ForeignKey(
        Category,
        related_name='post',
        on_delete=models.SET_NULL,
        null=True
    )
    tags = models.ManyToManyField(Tag, related_name='post')
    created_at = models.DateTimeField(auto_now_add=True)
    slug = models.SlugField(max_length=200, default='')

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse(
            'blog:post_single',
            kwargs={
                'slug': self.category.slug,
                'post_slug': self.slug
            }
        )

    def get_comments(self):
        return self.comment.all()

    class Meta:
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'


class Recipe(models.Model):
    """Модель рецептов"""
    name = models.CharField(max_length=100)
    servis = models.CharField(max_length=50)
    prep_time = models.PositiveIntegerField(default=0)
    cook_time = models.PositiveIntegerField(default=0)
    ingredients = RichTextField()
    directions = RichTextField()
    post = models.ForeignKey(
        Post,
        related_name='recipe',
        on_delete=models.SET_NULL,
        null=True,
        blank=True
    )

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Рецепт'
        verbose_name_plural = 'Рецепты'


class Comment(models.Model):
    """Модель комментариев"""
    name = models.CharField(max_length=50)
    email = models.EmailField(max_length=100)
    website = models.CharField(max_length=150, blank=True, null=True)
    message = models.TextField(max_length=500)
    created_at = models.DateTimeField(default=timezone.now)
    post = models.ForeignKey(Post, related_name='comment', on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'

povar_blog/blog/forms.py
from django import forms
from .models import Comment


class CommentForm(forms.ModelForm):
    """Форма комментария"""
    class Meta:
        model = Comment
        exclude = ['created_at', 'post']
        widgets = {
            'name': forms.TextInput(attrs={'placeholder': 'Name'}),
            'email': forms.EmailInput(attrs={'placeholder': 'Email'}),
            'website': forms.TextInput(attrs={'placeholder': 'Website'}),
            'message': forms.Textarea(attrs={'placeholder': 'Message'}),
        }

povar_blog/blog/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView, CreateView
from .models import *
from .forms import CommentForm


class HomeView(ListView):
    model = Post
    # paginate_by = 10
    template_name = 'blog/home.html'


class PostListView(ListView):
    """Вывод списка постов"""
    model = Post

    def get_queryset(self):
        return Post.objects.filter(category__slug=self.kwargs.get('slug')).select_related('category')


class PostDetailView(DetailView):
    """Вывод одного поста"""
    model = Post
    context_object_name = 'post'
    slug_url_kwarg = 'post_slug'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = CommentForm
        return context


class AddComment(CreateView):
    """Добавление комментария"""
    model = Comment
    form_class = CommentForm
    success_url = '/'

    def form_valid(self, form):
        form.instance.post_id = self.kwargs.get('pk')
        self.object = form.save()
        return super().form_valid(form)

    def get_success_url(self):
        return self.object.post.get_absolute_url()

povar_blog/templates/blog/include/left_nav.html
{% load menu_tags social_tags cache %}
{% cache 5000 left_nav %}
<div class="humberger__menu__overlay"></div>
    <div class="humberger__menu__wrapper">
        <div class="humberger__menu__logo">
            <a href="/"><img src="img/humberger/humberger-logo.png" alt=""></a>
        </div>
        <nav class="humberger__menu__nav mobile-menu">
            <ul>
                <li><a href="/">Главная</a></li>
                {% get_categories %}
                <li><a href="{% url 'contact:about' %}">О нас</a></li>
                <li><a href="{% url 'contact:contact' %}">Контакты</a></li>
            </ul>
        </nav>
        <div id="mobile-menu-wrap"></div>

        <div class="humberger__menu__about">
            <div class="humberger__menu__title sidebar__item__title">
                <h6>About me</h6>
            </div>
            {% get_about as about %}
            <img src="{{ about.get_first_image }}" alt="">
            <p>{{ about.mini_text|safe }}</p>
            <div class="humberger__menu__about__social sidebar__item__follow__links">
                {% get_social_links as social_links %}
                {% for item in social_links %}
                <a href="{{ item.link }}"><img class="contact_icon" src="{{ item.icon.url }}"></a>
                {% endfor %}
            </div>
        </div>

        <div class="humberger__menu__subscribe">
            <div class="humberger__menu__title sidebar__item__title">
                <h6>Subscribe</h6>
            </div>
            <p>Subscribe to our newsletter and get our newest updates right on your inbox.</p>
            <form action="#">
                <input type="text" class="email-input" placeholder="Your email">
                <label for="agree-check">
                    I agree to the terms & conditions
                    <input type="checkbox" id="agree-check">
                    <span class="checkmark"></span>
                </label>
                <button type="submit" class="site-btn">Subscribe</button>
            </form>
        </div>
    </div>
{% endcache %}

povar_blog/templates/blog/include/sidebar.html
{% load social_tags cache %}
{% cache 5000 sidebar %}
<div class="col-lg-4 col-md-4">
    <div class="sidebar__item">
        <div class="sidebar__about__item">
            <div class="sidebar__item__title">
                <h6>About me</h6>
            </div>
            {% get_about as about %}
            <img src="{{ about.get_first_image }}" alt="">
            <h6>Hi every one! I,m <span>{{ about.name }}</span></h6>
            <p>{{ about.mini_text|safe }}</p>
            <a href="{% url 'contact:about' %}" class="primary-btn">Read more</a>
        </div>
        <div class="sidebar__follow__item">
            <div class="sidebar__item__title">
                <h6>Follow me</h6>
            </div>
            <div class="sidebar__item__follow__links">
                {% get_social_links as social_links %}
                {% for item in social_links %}
                <a href="{{ item.link }}"><img src="{{ item.icon.url }}"></a>
                {% endfor %}
            </div>
        </div>

        <div class="sidebar__item__banner">
            <img src="static/img/sidebar/banner.jpg" alt="">
        </div>
        <div class="sidebar__item__categories">
            <div class="sidebar__item__title">
                <h6>Categories</h6>
            </div>
            {% include './sidebar_category.html' %}
        </div>
        <div class="sidebar__subscribe__item">
            <div class="sidebar__item__title">
                <h6>Subscribe</h6>
            </div>
            <p>Subscribe to our newsletter and get our newest updates right on your inbox.</p>
            <form action="#">
                <input type="text" class="email-input" placeholder="Your email">
                <label for="s-agree-check">
                    I agree to the terms & conditions
                    <input type="checkbox" id="s-agree-check">
                    <span class="checkmark"></span>
                </label>
                <button type="submit" class="site-btn">Subscribe</button>
            </form>
        </div>
    </div>
</div>
{% endcache %}

povar_blog/templates/blog/include/sidebar_category.html
{% load menu_tags mptt_tags %}
<ul>
    {% get_list_category as list_category %}
    {% for node in list_category %}
        <li> <a href="{% url 'blog:post_list' node.slug %}">{{ node.name }} <span>{{ node.post.count }}</span></a></li>
    {% endfor %}
</ul>

povar_blog/templates/blog/include/top_nav.html
{% load menu_tags cache %}
{% cache 5000 top_nav %}
<nav class="header__menu">
    <ul>
        <li class="active"><a href="/">Главная</a></li>
        {% get_last_posts %}
        {% get_categories %}

        <li><a href="{% url 'contact:about' %}">О нас</a></li>
        <li><a href="{% url 'contact:contact' %}">Контакты</a></li>
    </ul>
</nav>
{% endcache %}